machines:
  m0:
    capacity: 5
  m1:
    capacity: 1

processes:
  p0:
    order:
      - 0
      - 1
    number_of_parts: 1
  p1:
    order:
      - 0
      - 1
    number_of_parts: 1

operations:
  o0:
    required_machine: 0
    execution_time: 3
  o1:
    required_machine: 1
    execution_time: 5